### ISSUE TITLE
!plugin load 时报错，加载文件路径不存在

### ISSUE THREAD

**Issue by maiuyh456** [FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM#8]
2024-02-26 21:35:27.0603|ERROR|0|Plugin.StartInternal Plugin 'YunPlugin (BotPlugin)' failed to load: The type initializer for '<Module>' threw an exception..
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Costura.AssemblyLoader.Attach()
   at .cctor()

   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at TS3AudioBot.Dependency.InjectorExtensions.TryCreate(IInjector injector, Type type, Object& obj) in C:\projects\ts3audiobot\TS3AudioBot\Dependency\InjectorExtensions.cs:line 69
   at TS3AudioBot.Plugins.Plugin.CreatePluginObjects(IInjector injector, Type type, Boolean isStatic) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 427
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 369

**Comment by maiuyh456** [comment]
我是Ubuntu 20.04

**Comment by FiveHair** [comment]
试试这个版本https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/releases/download/2.0.3/YunPlugin-UNM.zip

**Comment by FiveHair** [comment]
![微信截图_20240407200050](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/16514929/99656c20-4911-4ac4-85c6-bc2d174ccada)

Linux工作正常，请检查一下您的运行环境。
